Fudee_v2/Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Fudee_v2.Models
{
    public class Category
    {
        [Key]
        [Display(Name = "Identyfikator kategorii:")]
        public int? IdCategory { get; set; }

        [Required(ErrorMessage = "Podaj nazwę kategorii.")]
        [Display(Name = "Nazwa kategorii")]
        [MaxLength(50, ErrorMessage = "Nazwa kategorii nie może być dłuższa niż 50 znaków.")]
        public string? NameCategory { get; set; }

        [Required(ErrorMessage = "Podaj opis kategorii.")]
        [Display(Name = "Opis kategorii:")]
        [MaxLength(300, ErrorMessage = "Opis kategorii nie może być dłuższa niż 300 znaków.")]
        public string? DescriptionCategoryy { get; set; }

        [Required(ErrorMessage = "Podaj nazwę ikony.")]
        [Display(Name = "Ikona kategorii:")]
        [MaxLength(30, ErrorMessage = "Nazwa ikony kategorii nie może być dłuższa niż 30 znaków.")]
        public string? Icon { get; set; }

        public virtual List<Restaurant>? Restaurants { get; set; }
    }
}

Fudee_v2/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fudee_v2.Data;
using Fudee_v2.Models;
using Microsoft.AspNetCore.Authorization;

namespace Fudee_v2.Controllers
{
   
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategory == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCategory,NameCategory,DescriptionCategoryy,Icon")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.ErrorMessage = "Taki rodzaj kuchni już istnieje!";
                return View("Create");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("IdCategory,NameCategory,DescriptionCategoryy,Icon")] Category category)
        {
            if (id != category.IdCategory)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.IdCategory))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        /*[Authorize(Roles = "admin")]*/
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategory == id);
            if (category == null)
            {
                return NotFound();
            }

            /*if (RestaurantsInCategory(id))
            {
                ViewBag.DeletMessage = "Nie można usunąć wybranej kuchni, ponieważ posiada przypisane restauracje";
            }*/

            return View(category);
        }

        // POST: Categories/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int? id)
        {
            return _context.Categories.Any(e => e.IdCategory == id);
        }

        private bool CategoryNameExists(string? name)
        {
            return (_context.Categories?.Any(e => e.NameCategory == name)).GetValueOrDefault();
        }

        private bool RestaurantsInCategory(int id)
        {
            return (_context.Categories?.Any(t => t.IdCategory == id)).GetValueOrDefault();
        }
    }
}

Fudee_v2/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fudee_v2.Data;
using Fudee_v2.Models;

namespace Fudee_v2.Controllers
{
    public class DishesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DishesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dishes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dishes.Include(d => d.Restaurant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Restaurant)
                .FirstOrDefaultAsync(m => m.IdDishes == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // GET: Dishes/Create
        public IActionResult Create()
        {
            ViewData["IdRestaurant"] = new SelectList(_context.Restaurants, "IdRestaurant", "DescriptionRestaurant");
            return View();
        }

        // POST: Dishes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDishes,ImageDish,NameDishes,DescriptionDishes,Price,IdRestaurant")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdRestaurant"] = new SelectList(_context.Restaurants, "IdRestaurant", "DescriptionRestaurant", dish.IdRestaurant);
            return View(dish);
        }

        // GET: Dishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes.FindAsync(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewData["IdRestaurant"] = new SelectList(_context.Restaurants, "IdRestaurant", "DescriptionRestaurant", dish.IdRestaurant);
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDishes,ImageDish,NameDishes,DescriptionDishes,Price,IdRestaurant")] Dish dish)
        {
            if (id != dish.IdDishes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DishExists(dish.IdDishes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdRestaurant"] = new SelectList(_context.Restaurants, "IdRestaurant", "DescriptionRestaurant", dish.IdRestaurant);
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Restaurant)
                .FirstOrDefaultAsync(m => m.IdDishes == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Dishes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Dishes'  is null.");
            }
            var dish = await _context.Dishes.FindAsync(id);
            if (dish != null)
            {
                _context.Dishes.Remove(dish);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
          return _context.Dishes.Any(e => e.IdDishes == id);
        }
    }
}

Fudee_v2/Views/Categories/Create.cshtml
@model Fudee_v2.Models.Category

@{
    ViewData["Title"] = "Dodaj";
}

<h1 class="text-primary popins">Nowa</h1>
@{
    if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <div class="alert alert alert-danger" role="alert">@ViewBag.ErrorMessage</div>
    }
}
<h4 class="text-success"><b>Kategoria</b></h4>
<hr />
<div class="row">
    <div class="col-md-4 interspace">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameCategory" class="control-label"></label>
                <input asp-for="NameCategory" class="form-control" />
                <span asp-validation-for="NameCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionCategoryy" class="control-label"></label>
                <textarea asp-for="DescriptionCategoryy" class="form-control"></textarea>
                <span asp-validation-for="DescriptionCategoryy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input type="file" name="picture" id="picture" class="form-control" accept=".jpg,.gif,.png" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-light">Powrót do listy</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
}

Fudee_v2/Views/Categories/Delete.cshtml
@model Fudee_v2.Models.Category

@{
    ViewData["Title"] = "Usuwanie";
}

<h1 class="text-primary popins">Usuwanie</h1>

@{
    if (!String.IsNullOrEmpty(ViewBag.DeleteMessage))
    {
        <h5 class="alert alert-danger" role="alert"><i class="bi-info-circle"></i>&nbsp@ViewBag.DeleteMessage</h5>
    }
    else
    {
        <h5 class="alert alert-danger" role="alert"><i class="bi-info-circle"></i>&nbsp;Czy napewno chcesz usunąć tę kategorię?</h5>

    }
}


<div>
    <h4 class="text-success"><b>Kategoria</b></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NameCategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NameCategory)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionCategoryy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescriptionCategoryy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Icon)
        </dd>
    </dl>

    <form asp-action="Delete">
        @{
            if (String.IsNullOrEmpty(ViewBag.DeleteMessage))
            {
                <input type="hidden" asp-for="IdCategory" />
                <input type="submit" value="Usuń" class="btn btn-danger" />

            }
        }

        <a asp-action="Index" class="btn btn-light">Powrót do listy</a>
    </form>
</div>

Fudee_v2/Views/Categories/Details.cshtml
@model Fudee_v2.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NameCategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NameCategory)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionCategoryy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescriptionCategoryy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd class="col-sm-10">
           
            <img class="img-fluid mt-3" src="~/graphic/@Model.Icon"><br />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.IdCategory">Edycja</a> |
    <a asp-action="Index" class="btn btn-light">Powrót do listy</a>
</div>

Fudee_v2/Views/Categories/Edit.cshtml
@model Fudee_v2.Models.Category

@{
    ViewData["Title"] = "Edycja";
}

<h1 class="text-primary popins">Edycja</h1>

<h4 class="text-success"><b>Kategoria</b></h4>
<hr />
<div class="row">
    <div class="col-md-4 interspace">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdCategory" />
            <div class="form-group">
                <label asp-for="NameCategory" class="control-label"></label>
                <input asp-for="NameCategory" class="form-control" />
                <span asp-validation-for="NameCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionCategoryy" class="control-label"></label>
                <textarea asp-for="DescriptionCategoryy" class="form-control"></textarea>
                <span asp-validation-for="DescriptionCategoryy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input type="file" name="picture" id="picture" class="form-control" accept=".jpg,.gif,.png" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-light">Powrót do listy</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Fudee_v2/Views/Categories/Index.cshtml
@model IEnumerable<Fudee_v2.Models.Category>

@{
    ViewData["Title"] = "Rodzaje kuchni";
}

<h1>Rodzaje kuchni</h1>

<p>
    <a asp-action="Create">Nowa kuchnia</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescriptionCategoryy)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>

                    <i class="bi-@item.Icon"></i><br />
                    <img src="@Url.Content("~/graphic/"+item.Icon)" class="img-fluid" alt="@item.NameCategory" width="150" />

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescriptionCategoryy)
                </td>

                <td>
                         <a asp-area="" asp-controller="Dishes" asp-action="Index">Dania</a>
                    @{
                    if(User.IsInRole("admin")||User.IsInRole("restaurator"))
                    {
                        <a asp-action="Details" asp-route-id="@item.IdCategory">Szczegóły</a> 
                     
                        if(User.IsInRole("admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.IdCategory">Edytuj</a> 
                            <a asp-action="Delete" asp-route-id="@item.IdCategory">Usunięcie</a>
                        }
                       
                    }
                    }
                    
                </td>
            </tr>
        }
    </tbody>
</table>